// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package secondmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the SecondModule module
	public static java.math.BigDecimal calculateTotalRevenue(IContext context, myfirstmodule.proxies.SalesTrackingTable _salesTrackingTable)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("SalesTrackingTable", _salesTrackingTable == null ? null : _salesTrackingTable.getMendixObject());
			return (java.math.BigDecimal)Core.execute(context, "SecondModule.CalculateTotalRevenue", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.Long countSalesOrders(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			return (java.lang.Long)Core.execute(context, "SecondModule.CountSalesOrders", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void deleteListViewItem(IContext context, myfirstmodule.proxies.SalesTrackingTableTemporary _salesTrackingTableTemporary)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("SalesTrackingTableTemporary", _salesTrackingTableTemporary == null ? null : _salesTrackingTableTemporary.getMendixObject());
			Core.execute(context, "SecondModule.DeleteListViewItem", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean getDeleted(IContext context, myfirstmodule.proxies.SalesTrackingTable _salesTrackingTable)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("SalesTrackingTable", _salesTrackingTable == null ? null : _salesTrackingTable.getMendixObject());
			return (java.lang.Boolean)Core.execute(context, "SecondModule.GetDeleted", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}