// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Root
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject rootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Root";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Ip("Ip"),
		Query("Query"),
		Status("Status"),
		Country("Country"),
		CountryCode("CountryCode"),
		Region("Region"),
		RegionName("RegionName"),
		City("City"),
		Zip("Zip"),
		Lat("Lat"),
		Lon("Lon"),
		Timezone("Timezone"),
		Isp("Isp"),
		Org("Org"),
		As("As");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Root(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Root"));
	}

	protected Root(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject rootMendixObject)
	{
		if (rootMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Root", rootMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Root");

		this.rootMendixObject = rootMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Root.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Root.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Root(context, mendixObject);
	}

	public static myfirstmodule.proxies.Root load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Root.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Ip
	 */
	public final java.lang.String getIp()
	{
		return getIp(getContext());
	}

	/**
	 * @param context
	 * @return value of Ip
	 */
	public final java.lang.String getIp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Ip.toString());
	}

	/**
	 * Set value of Ip
	 * @param ip
	 */
	public final void setIp(java.lang.String ip)
	{
		setIp(getContext(), ip);
	}

	/**
	 * Set value of Ip
	 * @param context
	 * @param ip
	 */
	public final void setIp(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ip)
	{
		getMendixObject().setValue(context, MemberNames.Ip.toString(), ip);
	}

	/**
	 * @return value of Query
	 */
	public final java.lang.String getQuery()
	{
		return getQuery(getContext());
	}

	/**
	 * @param context
	 * @return value of Query
	 */
	public final java.lang.String getQuery(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Query.toString());
	}

	/**
	 * Set value of Query
	 * @param query
	 */
	public final void setQuery(java.lang.String query)
	{
		setQuery(getContext(), query);
	}

	/**
	 * Set value of Query
	 * @param context
	 * @param query
	 */
	public final void setQuery(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String query)
	{
		getMendixObject().setValue(context, MemberNames.Query.toString(), query);
	}

	/**
	 * @return value of Status
	 */
	public final java.lang.String getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final java.lang.String getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Status.toString());
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(java.lang.String status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status)
	{
		getMendixObject().setValue(context, MemberNames.Status.toString(), status);
	}

	/**
	 * @return value of Country
	 */
	public final java.lang.String getCountry()
	{
		return getCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of Country
	 */
	public final java.lang.String getCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Country.toString());
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final void setCountry(java.lang.String country)
	{
		setCountry(getContext(), country);
	}

	/**
	 * Set value of Country
	 * @param context
	 * @param country
	 */
	public final void setCountry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String country)
	{
		getMendixObject().setValue(context, MemberNames.Country.toString(), country);
	}

	/**
	 * @return value of CountryCode
	 */
	public final java.lang.String getCountryCode()
	{
		return getCountryCode(getContext());
	}

	/**
	 * @param context
	 * @return value of CountryCode
	 */
	public final java.lang.String getCountryCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CountryCode.toString());
	}

	/**
	 * Set value of CountryCode
	 * @param countrycode
	 */
	public final void setCountryCode(java.lang.String countrycode)
	{
		setCountryCode(getContext(), countrycode);
	}

	/**
	 * Set value of CountryCode
	 * @param context
	 * @param countrycode
	 */
	public final void setCountryCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String countrycode)
	{
		getMendixObject().setValue(context, MemberNames.CountryCode.toString(), countrycode);
	}

	/**
	 * @return value of Region
	 */
	public final java.lang.String getRegion()
	{
		return getRegion(getContext());
	}

	/**
	 * @param context
	 * @return value of Region
	 */
	public final java.lang.String getRegion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Region.toString());
	}

	/**
	 * Set value of Region
	 * @param region
	 */
	public final void setRegion(java.lang.String region)
	{
		setRegion(getContext(), region);
	}

	/**
	 * Set value of Region
	 * @param context
	 * @param region
	 */
	public final void setRegion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String region)
	{
		getMendixObject().setValue(context, MemberNames.Region.toString(), region);
	}

	/**
	 * @return value of RegionName
	 */
	public final java.lang.String getRegionName()
	{
		return getRegionName(getContext());
	}

	/**
	 * @param context
	 * @return value of RegionName
	 */
	public final java.lang.String getRegionName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RegionName.toString());
	}

	/**
	 * Set value of RegionName
	 * @param regionname
	 */
	public final void setRegionName(java.lang.String regionname)
	{
		setRegionName(getContext(), regionname);
	}

	/**
	 * Set value of RegionName
	 * @param context
	 * @param regionname
	 */
	public final void setRegionName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String regionname)
	{
		getMendixObject().setValue(context, MemberNames.RegionName.toString(), regionname);
	}

	/**
	 * @return value of City
	 */
	public final java.lang.String getCity()
	{
		return getCity(getContext());
	}

	/**
	 * @param context
	 * @return value of City
	 */
	public final java.lang.String getCity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.City.toString());
	}

	/**
	 * Set value of City
	 * @param city
	 */
	public final void setCity(java.lang.String city)
	{
		setCity(getContext(), city);
	}

	/**
	 * Set value of City
	 * @param context
	 * @param city
	 */
	public final void setCity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String city)
	{
		getMendixObject().setValue(context, MemberNames.City.toString(), city);
	}

	/**
	 * @return value of Zip
	 */
	public final java.lang.String getZip()
	{
		return getZip(getContext());
	}

	/**
	 * @param context
	 * @return value of Zip
	 */
	public final java.lang.String getZip(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Zip.toString());
	}

	/**
	 * Set value of Zip
	 * @param zip
	 */
	public final void setZip(java.lang.String zip)
	{
		setZip(getContext(), zip);
	}

	/**
	 * Set value of Zip
	 * @param context
	 * @param zip
	 */
	public final void setZip(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String zip)
	{
		getMendixObject().setValue(context, MemberNames.Zip.toString(), zip);
	}

	/**
	 * @return value of Lat
	 */
	public final java.math.BigDecimal getLat()
	{
		return getLat(getContext());
	}

	/**
	 * @param context
	 * @return value of Lat
	 */
	public final java.math.BigDecimal getLat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Lat.toString());
	}

	/**
	 * Set value of Lat
	 * @param lat
	 */
	public final void setLat(java.math.BigDecimal lat)
	{
		setLat(getContext(), lat);
	}

	/**
	 * Set value of Lat
	 * @param context
	 * @param lat
	 */
	public final void setLat(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal lat)
	{
		getMendixObject().setValue(context, MemberNames.Lat.toString(), lat);
	}

	/**
	 * @return value of Lon
	 */
	public final java.math.BigDecimal getLon()
	{
		return getLon(getContext());
	}

	/**
	 * @param context
	 * @return value of Lon
	 */
	public final java.math.BigDecimal getLon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Lon.toString());
	}

	/**
	 * Set value of Lon
	 * @param lon
	 */
	public final void setLon(java.math.BigDecimal lon)
	{
		setLon(getContext(), lon);
	}

	/**
	 * Set value of Lon
	 * @param context
	 * @param lon
	 */
	public final void setLon(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal lon)
	{
		getMendixObject().setValue(context, MemberNames.Lon.toString(), lon);
	}

	/**
	 * @return value of Timezone
	 */
	public final java.lang.String getTimezone()
	{
		return getTimezone(getContext());
	}

	/**
	 * @param context
	 * @return value of Timezone
	 */
	public final java.lang.String getTimezone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Timezone.toString());
	}

	/**
	 * Set value of Timezone
	 * @param timezone
	 */
	public final void setTimezone(java.lang.String timezone)
	{
		setTimezone(getContext(), timezone);
	}

	/**
	 * Set value of Timezone
	 * @param context
	 * @param timezone
	 */
	public final void setTimezone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String timezone)
	{
		getMendixObject().setValue(context, MemberNames.Timezone.toString(), timezone);
	}

	/**
	 * @return value of Isp
	 */
	public final java.lang.String getIsp()
	{
		return getIsp(getContext());
	}

	/**
	 * @param context
	 * @return value of Isp
	 */
	public final java.lang.String getIsp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Isp.toString());
	}

	/**
	 * Set value of Isp
	 * @param isp
	 */
	public final void setIsp(java.lang.String isp)
	{
		setIsp(getContext(), isp);
	}

	/**
	 * Set value of Isp
	 * @param context
	 * @param isp
	 */
	public final void setIsp(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String isp)
	{
		getMendixObject().setValue(context, MemberNames.Isp.toString(), isp);
	}

	/**
	 * @return value of Org
	 */
	public final java.lang.String getOrg()
	{
		return getOrg(getContext());
	}

	/**
	 * @param context
	 * @return value of Org
	 */
	public final java.lang.String getOrg(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Org.toString());
	}

	/**
	 * Set value of Org
	 * @param org
	 */
	public final void setOrg(java.lang.String org)
	{
		setOrg(getContext(), org);
	}

	/**
	 * Set value of Org
	 * @param context
	 * @param org
	 */
	public final void setOrg(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String org)
	{
		getMendixObject().setValue(context, MemberNames.Org.toString(), org);
	}

	/**
	 * @return value of As
	 */
	public final java.lang.String getAs()
	{
		return getAs(getContext());
	}

	/**
	 * @param context
	 * @return value of As
	 */
	public final java.lang.String getAs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.As.toString());
	}

	/**
	 * Set value of As
	 * @param as
	 */
	public final void setAs(java.lang.String as)
	{
		setAs(getContext(), as);
	}

	/**
	 * Set value of As
	 * @param context
	 * @param as
	 */
	public final void setAs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String as)
	{
		getMendixObject().setValue(context, MemberNames.As.toString(), as);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return rootMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Root that = (myfirstmodule.proxies.Root) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Root";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
