// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package secondmodule.proxies;

public class SalesDeletedHistory
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject salesDeletedHistoryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SecondModule.SalesDeletedHistory";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SalesId("SalesId"),
		OrderQuantity("OrderQuantity");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SalesDeletedHistory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SecondModule.SalesDeletedHistory"));
	}

	protected SalesDeletedHistory(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject salesDeletedHistoryMendixObject)
	{
		if (salesDeletedHistoryMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SecondModule.SalesDeletedHistory", salesDeletedHistoryMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SecondModule.SalesDeletedHistory");

		this.salesDeletedHistoryMendixObject = salesDeletedHistoryMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SalesDeletedHistory.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static secondmodule.proxies.SalesDeletedHistory initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return secondmodule.proxies.SalesDeletedHistory.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static secondmodule.proxies.SalesDeletedHistory initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new secondmodule.proxies.SalesDeletedHistory(context, mendixObject);
	}

	public static secondmodule.proxies.SalesDeletedHistory load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return secondmodule.proxies.SalesDeletedHistory.initialize(context, mendixObject);
	}

	public static java.util.List<secondmodule.proxies.SalesDeletedHistory> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<secondmodule.proxies.SalesDeletedHistory> result = new java.util.ArrayList<secondmodule.proxies.SalesDeletedHistory>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//SecondModule.SalesDeletedHistory" + xpathConstraint))
			result.add(secondmodule.proxies.SalesDeletedHistory.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of SalesId
	 */
	public final java.lang.Integer getSalesId()
	{
		return getSalesId(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesId
	 */
	public final java.lang.Integer getSalesId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SalesId.toString());
	}

	/**
	 * Set value of SalesId
	 * @param salesid
	 */
	public final void setSalesId(java.lang.Integer salesid)
	{
		setSalesId(getContext(), salesid);
	}

	/**
	 * Set value of SalesId
	 * @param context
	 * @param salesid
	 */
	public final void setSalesId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer salesid)
	{
		getMendixObject().setValue(context, MemberNames.SalesId.toString(), salesid);
	}

	/**
	 * @return value of OrderQuantity
	 */
	public final java.lang.Integer getOrderQuantity()
	{
		return getOrderQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderQuantity
	 */
	public final java.lang.Integer getOrderQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.OrderQuantity.toString());
	}

	/**
	 * Set value of OrderQuantity
	 * @param orderquantity
	 */
	public final void setOrderQuantity(java.lang.Integer orderquantity)
	{
		setOrderQuantity(getContext(), orderquantity);
	}

	/**
	 * Set value of OrderQuantity
	 * @param context
	 * @param orderquantity
	 */
	public final void setOrderQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer orderquantity)
	{
		getMendixObject().setValue(context, MemberNames.OrderQuantity.toString(), orderquantity);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return salesDeletedHistoryMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final secondmodule.proxies.SalesDeletedHistory that = (secondmodule.proxies.SalesDeletedHistory) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SecondModule.SalesDeletedHistory";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
